---
- name: Show successful approvals for audit
  hosts: all

  tasks:
    - name: show job list
      ansible.controller.job_list:
        status: successful
        validate_certs: false
        controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
        controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
        #query: {"summary_fields.source_workflow_job.name": "Multi Hypervisor Create & Config VM, Deploy Web App with Failure Paths Citrix"}
        all_pages: true
      register: r_job_output

    - name: Job summary fields
      debug:  
        msg: "{{ item.summary_fields.source_workflow_job.name }}"
      loop: "{{ r_job_output.results }}"
      when: item.summary_fields.source_workflow_job.name is defined
      register: r_src_wfjt_name

    - name: initialize workflow_names as an empty list
      set_fact:
        workflow_info: []

#    - name: load wfjt names into list
#      set_fact:
#        workflow_info: "{{ workflow_info + [ item.summary_fields.source_workflow_job.name, item.summary_fields.source_workflow_job.id ] }}" 
#      loop: "{{ r_job_output.results }}"
#      when: item.summary_fields.source_workflow_job.name is defined

    - name: load wfjt names into list
      set_fact:
        workflow_info: "{{ workflow_info + [ {'name' : item.summary_fields.source_workflow_job.name, 'id' : item.summary_fields.source_workflow_job.id } ] }}" 
      loop: "{{ r_job_output.results }}"
      when: item.summary_fields.source_workflow_job.name is defined
      # good post on appending dictionaries to list: https://www.middlewareinventory.com/blog/ansible-list-examples-how-to-create-and-append-items-to-list/

    - name: make workflow_info unique
      set_fact: 
        workflow_info: "{{ wofkflow_info | unique }}"

    - name: show wfjt names
      debug:
        var: workflow_info
        
#    - name: show r_job_output
#      debug:
#        var: r_job_output.summary_fields.source_workflow_job.name
#      loop: "{{ r_job_output }}"
#      when: r_job_output.summary_fields.source_workflow_job.id == 41004
