---
- name: Show successful approvals for audit
  hosts: all

  tasks:
    - name: show job list
      ansible.controller.job_list:
        status: successful
        validate_certs: false
        controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
        controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
        #query: {"summary_fields.source_workflow_job.name": "Multi Hypervisor Create & Config VM, Deploy Web App with Failure Paths Citrix"}
        all_pages: true
      register: r_job_output

    - name: what does dict2items coversion look like
      debug:  
        var: dict2items | r_job_output

#    - name: show r_job_output
#      debug:
#        var: r_job_output.summary_fields.source_workflow_job.name
#      loop: "{{ r_job_output }}"
#      when: r_job_output.summary_fields.source_workflow_job.id == 41004