---
- name: Show successful approvals for audit
  hosts: all

  tasks:
    - name: show job list
      ansible.controller.job_list:
        status: successful
        validate_certs: false
        controller_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
        controller_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        controller_host: "{{ lookup('env', 'TOWER_HOST') }}"
        query: {"Workflow Job Template": "Multi Hypervisor Create & Config VM, Deploy Web App with Failure Paths Citrix"}
        #query: {"playbook": "testing.yml"}
        #tower_config_file: "~/tower_cli.cfg"
      register: r_job_output

    - name: show r_job_output
      debug:
        var: r_job_output 