---
- name: get approvals list
  hosts: localhost

  tasks:
    - name: Workflow Approvals
      uri:
        url: "https://54.172.168.17/api/v2/workflow_approvals/"
        method: GET
        return_content: yes
        headers: 
          Authorization: Bearer {{ authtoken }}
        validate_certs: False
        status_code:
          - 200
      register: r_api_approval_output

    - name: show api approval output
      debug:
        msg: | 
          ---------------
          "ID: {{ item.id }} WFJT_Name: {{item.summary_fields.workflow_job_template.name}}"
          "Approval Node: {{ item.summary_fields.workflow_approval_template.name }}"
          ""
      loop: "{{ r_api_approval_output }}"

#    - name: get authtoken
#      uri:
#        url: https://54.172.168.17/api/v2/tokens/
#        method: POST
#        body: '{ "username": "{{tower_user}}", "password": "{{tower_password}}" }'
#        body_format: json
#        validate_certs: no
#      register: authtoken